const list = [
  "Home",
  "Gestão do condomínio",
  "Reserva",
  "Correspondências",
  "Arquivo digital",
  "Lista de tarefas",
  "Atividades",
  "Usuários",
  "Fornecedores/Orçamento",
  "Segurança & Portaria",
  "Controle de acesso",
  "Visitante fixo",
  "Areas de acesso",
  "Veículos",
  "Recados",
  "Comunicação",
  "Comunicados",
  "Ocorrências",
  "Mural/Classificados",
  "Enquetes",
  "Configurações",
];
